image: php:7.2

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - staging
  - production

staging:
  type: deploy
  stage: staging
  script:
    - apt-get update -qq
    - apt-get install -y -qq git
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.staging .env
    - php artisan key:generate
    - vendor/bin/phpunit tests
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging

production:
  type: deploy
  stage: production
  script:
    - apt-get update -qq
    - apt-get install -y -qq git
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.production .env
    - php artisan key:generate
    - vendor/bin/phpunit tests
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
