query CountriesList {
    countriesList {
        country {
            name
            code
        }
        stats {
            new_confirmed
            total_confirmed
            new_deaths
            total_deaths
            new_recovered
            total_recovered
        }
    }
}
